### PR TITLE
Add creating rooms and inviting to them to the featureset

### PR DESCRIPTION
**Pull request by berlincount**
While working on a testsuite for a bot I've found the need to be able to create rooms and invite the bot to them.

This code:

- fixes some typos
- adds `--room-create` and `--room-invite` commandline options
- requires sending a message when doing either of those actions
- makes log messages for sending files/messages visible at `info` log level already

### CODE REVIEW

**Comment by 8go** [comment]
Excellent work.

Thank you so much @berlincount 
I love it. Very helpful, it will be useful to many people!

lgtm

**Comment by 8go** [comment]
@berlincount May I ask you why you combined the --room-create and --room-invite commandline options with sending a message. What was your thinking behind that? What is the advantage of this over having them stand-alone (without sending a message)? I am curious. 

Thanks again.

**Comment by berlincount** [comment]
Main reason was the existing cumbersome code structure, combined with my lazyness 😬

**Comment by 8go** [comment]
Thanks for the response @berlincount . That clarified things for me. Thanks.

I added new features such as room_join, room_leave, room_forget, room_ban, room_unban, room_kick, etc.
Your room_create now also allows adding room name and room topic.

Furthermore, your room_create and room_invite are separated from sending messages. All of the room_* features are
separated from send and listen.

Also the change is slightly incompatible, your invite was like this:

OLD:: matrix-commander.py --room-invite user1 user2 --room room1 room2

Now it is:

NEW:: matrix-commander.py --room-invite room1 room2 --user user1 user2

as this schema fits better with the rest of the room_* calls.

Please check out the new version and enjoy!

**Pull request merged**
